# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f89c020787c4d8e203a682343e5413e272ff661afbd2a2c8c0effc8509c55fc82d7367106c6b4429c130a0febb6c3ca32f6e4dde699d3e64cf56fbd8dd2af5

test:
  secret_key_base: 09dafad2430395bc98ddd845b7a48449bd24982aa75546d4a1898baabfa0ab2bbb9138fcb7947240b58064f90c638bb75096c838e29dc1741cf4d38607f613b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
